### ISSUE TITLE
On-Demand Injection

### ISSUE THREAD

**Issue by ianhe8x** [cennznet/singlesource-extension#10]
note: this is a breaking change to injected interface.

similar to what metamask or polkadot-extension does, dapp need to request access to the signer and user can decide to accept or reject.

new injected interface: 
```
window.cennznetInjected {
  [name: string]: {
    version: 'semver';
    async enable(): Promise<CennznetInjected>;
  }
}
```
when call enable(): ui will give three options:
reject, accept once, accept always
store permission for accept always. (use domain as key of permission)

```
interface CennznetInjected {
  signer: Signer;
  accounts$: Observable<Account[]>;
  accounts: Account[];
}

interface SingleSourceInjected extends CennznetInjected {
  //isConnected$: Observable<boolean>;
  //isConnected: boolean;
  isPaired$: Observable<boolean>;
  isPaired: boolean;
  pairedDevice$: Observable<{
    version: string;
    id: string;
  }>;
  pairedDevice;
}
```

**Comment by xlc** [comment]
instead of calling `cennznetInjected`, better to use a generic term like `singleSourceInjected` for better compatibility with other networks

**Comment by ianhe8x** [comment]
@xlc, So here's the problem, for dapp developer, how they are going to search available signer, by network name or by signer name?
I think it should be the first one, that's why named after network is more generic.

Situation is 
1. a signer can support multiple networks
2. a dapp is usually only targeted on one network
3. dapp wants to search all available signers on his target network and chose one from them to use (or let user chose)

**Comment by xlc** [comment]
A possible solution is have a common
```
web3injected = {
  registerSigner: (signer) => void,
  getSigner(network) => Signer[]
}

type Signer = {
  supportNetwork(network) => bool,
  // other signer methods
}
```

Each injected JS will check if `web3injected` exists, then just `web3injected. registerSigner(signer)` or if `web3injected` not exists, provide an implementation of it and register itself as well. dApp will just use `web3injected.getSigner('cennzet')[0]`

Then we can easily have one signer support multiple networks

This is something we can should discuss with Jaco

**Comment by ianhe8x** [comment]
then who is responsible to bring `web3injected` into page context.
Or rather if we should bind ourselves that close to theirs.

**Comment by xlc** [comment]
any spec (to be defined) confirming extension can inject it

**Comment by ianhe8x** [comment]
The way this ticket suggests also works, 
Each injected JS, if it supports polkadot, then put itself into web3injected. If it happens to support cennznet as well, then it need to put itself into cennznetInjected.

For singlesource-extension, we will put ourselves into web3injected when we are ready.

you don't really need `register` and `getSigner()`, only simply search the relative global.

**Comment by AlexZhenWang** [comment]
- [x] Updating injected interface
- [ ] Updating content script - initializing after the authorization.
- [ ] Updating chang log
